name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libboost-dev libjsoncpp-dev pkg-config
    
    - name: Create build directory
      run: mkdir build
    
    - name: Configure CMake
      run: cmake -B build -S .
    
    - name: Build
      run: cmake --build build
    
    - name: Test (optional)
      run: |
        cd build
        # Add your test commands here if you have any
        # ctest
    
    - name: Upload artifacts (optional)
      uses: actions/upload-artifact@v3
      with:
        name: hoshimi-executable
        path: build/bin/Hoshimi
