name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libboost-dev libjsoncpp-dev pkg-config libcjson-dev lbsndfile1-dev
    
    - name: Create build directory
      run: mkdir build
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release --target all
    
    - name: Test (optional)
      run: |
        cd build
        # This will come soon
        
    
    - name: Upload artifacts (optional)
      uses: actions/upload-artifact@v4
      with:
        name: hoshimi-executable
        path: build/bin/hoshimi
