on:
  push:
    tags:
      - 'v*' 

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Font consistency across dotfiles
            - gtk and qt6/qt5 themes writing
            - Update schema to compensate 
            - Equibop writing and custom theme

            - Added specific package aliases, for example terminal would mean all the terminals, qs would mean quickshell
            - Added the ability to write variables from the program
            - Added the ability to write when colors satisfy certain properties

            - Added the hoshimi-daemon, a powerful tool to help relieve manual adjustments between the dotfiles and source
            - Added the ability to unzip .osk files instead of having the unzipped
          draft: false
          prerelease: true
