name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: '.'
        exclude: './lib'
        extensions: 'h,cpp,c'
        clangFormatVersion: 20
        inplace: True
    - uses: EndBug/add-and-commit@v9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        author_name: Matercan
        author_email: matercan@proton.me 
        commit: --sign-ff
        committer_name: Clang Robot
        message: "Fix: clang format"
      
